# Kotlin Multiplatform

# Android
android.useAndroidX=true
android.enableJetifier=false
android.suppressUnsupportedCompileSdk=34
android.nonTransitiveRClass=true

# KSP (if needed for Room, etc)
# ksp.incremental=true
# ksp.interop=true

# JVM
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true